=== abdelalimah/XML/public/examsSolutions/2015/livres.dtd
<!ELEMENT liste (livre+)>
<!ELEMENT livre (titre,auteurs,editeur,date-edition,theme,resumes*,image,fichiers*)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteurs (auteur+)>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT date-edition (#PCDATA)>
<!ELEMENT theme (#PCDATA)>
<!ELEMENT resumes (resume+)>
<!ELEMENT resume (#PCDATA)>
<!ELEMENT image EMPTY>
<!ELEMENT fichiers (fichier)>
<!ELEMENT fichier (#PCDATA)>


<!ATTLIST livre code ID #REQUIRED>
<!ATTLIST resume langue CDATA "Ar" >
<!ATTLIST image source CDATA #REQUIRED>
<!ATTLIST fichier chemin CDATA #REQUIRED>

=== abdelalimah/XML/public/examsSolutions/2015/livres.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE liste SYSTEM "./livres.dtd"> -->
<?xml-stylesheet href="./livres.xsl" type="text/xsl"?>
<liste xsi:noNamespaceSchemaLocation="./livres.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <livre code="L00001">
        <titre>Maitriser XML</titre>
        <auteurs>
            <auteur>Katib Moufid</auteur>
            <auteur>Katib Hakim</auteur>
        </auteurs>
		<editeur>Dar Al-Ilm </editeur>
		<date-edition>2015</date-edition>
        <theme>XML</theme>
        <resumes>
            <resume>XML هذا الكتاب يسلط الضوء على المفاهيم الأساسية ل</resume>
            <resume langue="Fr">Ce livre donne les notions fondamentales de XML</resume>
            <resume langue="En">This book gives the basic concepts of XML</resume>
        </resumes>
        <image source="./download.png" />
        <fichiers>
            <fichier chemin="L00001.doc" />		
        </fichiers>
	</livre>

	<livre code="L00002">
        <titre>Tous sur XML</titre>
        <auteurs>
            <auteur>Katib Moufid</auteur>
        </auteurs>
		<editeur>Dar Al-Ilm </editeur>
		<date-edition>2016</date-edition>
		<theme>Blah</theme>
		<image source="photos/L00002.jpg" />		
	</livre>

	<livre  code="L00003">
        <titre>Tous sur les Bases de données</titre>
        <auteurs>
            
            <auteur>Katib Hakim</auteur>
        </auteurs>
		<editeur>Dar Al-Ilm </editeur>
		<date-edition>2015</date-edition>
        <theme>BD</theme>
        <resumes>

            <resume langue = "Fr">Vous trouvez dans ce livre tous ce que vous voulez sur les bases de données</resume>		
        </resumes>
		<image source="photos/L00003.jpg" />
	</livre>
</liste>
