=== abdelalimah/XML/public/examsSolutions/2019/fsML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- elements-->

    <xsd:element name="racine">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="dossier" minOccurs="1" maxOccurs="unbounded"></xsd:element>
                <xsd:element ref="fichier" minOccurs="1" maxOccurs="unbounded"></xsd:element>
                <xsd:element ref="profile" minOccurs="1" maxOccurs="unbounded"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="dossier" type="dossierType" />
    <xsd:element name="fichier" type="fichierType" />

    <!--  -->

    <!-- shared informations -->

    <xsd:complexType name="baseInfo">
        <xsd:attribute name="id" type="idtype" use="required"></xsd:attribute>
        <xsd:attribute name="nom" type="nomtype" use="required"></xsd:attribute>
        <xsd:attribute name="creation" type="creationtype" use="required"></xsd:attribute>
    </xsd:complexType>

    <!--  -->

    <!-- type definitions -->

    <xsd:simpleType name="tailletype">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\d{2}"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="idtype">
        <xsd:restriction base="xsd:ID">
            <xsd:pattern value="[A-Z]\d{1}"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="nomtype">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="20"></xsd:maxLength>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="creationtype">
        <xsd:restriction base="xsd:int">
            <xsd:totalDigits value="4"></xsd:totalDigits>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="datefichiertype">
        <xsd:restriction base="xsd:int">
            <xsd:totalDigits value="4"></xsd:totalDigits>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="dossierType">
        <xsd:complexContent>
            <xsd:extension base="baseInfo">
                <xsd:sequence>
                    <xsd:element ref="dossier" minOccurs="0" maxOccurs="unbounded"></xsd:element>
                    <xsd:element ref="fichier" minOccurs="0" maxOccurs="unbounded"></xsd:element>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="fichierType">
        <xsd:complexContent>
            <xsd:extension base="baseInfo">
                <xsd:attribute name="dateModification" type="datefichiertype" use="required"></xsd:attribute>
                <xsd:attribute name="taille" type="tailletype" use="required"></xsd:attribute>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <!--  -->
    <xsd:element name="profile">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="xsd:string">
                    <xsd:attribute name="id"></xsd:attribute>
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== abdelalimah/XML/public/examsSolutions/2019/fsML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./style.xsl" type="text/xsl"?>
<racine xsi:noNamespaceSchemaLocation="./fsML.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <dossier id="D1" nom="pics" creation="2018">
        <dossier id="D6" nom="Mql" creation="2018"></dossier>
        <dossier id="D2" nom="Wisd" creation="2018"></dossier>
        <fichier id="F1" nom="Midvi" creation="2000" dateModification="2010" taille="30"></fichier>

    </dossier>
    <dossier id="D3" nom="pics" creation="2018">
        <dossier id="D4" nom="otherMql" creation="2021"></dossier>
        <fichier id="F2" nom="otherWisd" creation="2000" dateModification="2010" taille="30"></fichier>
    </dossier>
    <fichier id="F3" nom="pics" creation="2020" dateModification="2018" taille="20"></fichier>
    <profile id="E2">blahblah</profile>
</racine>
