=== abdelalimah/XML/public/reproduction/2012/articles.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="articles">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="article" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="reference" type="xs:string"></xs:element>
                            <xs:element name="intitule" type="xs:string"></xs:element>
                            <xs:element name="prixTTC" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="cat" type="xs:ID"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== abdelalimah/XML/public/reproduction/2012/articles.xml
<?xml version="1.0" encoding="UTF-8"?>

<articles xsi:noNamespaceSchemaLocation="./articles.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <article cat="C1">
        <reference>P01</reference>
        <intitule>PC Portable</intitule>
        <prixTTC>8400.20</prixTTC>
    </article>
    <article cat="C2">
        <reference>P01</reference>
        <intitule>Imprimante</intitule>
        <prixTTC>7000.20</prixTTC>
    </article>
</articles>
