=== abdelalimah/XML/public/reproduction/2012/catalogue.dtd
<!ELEMENT catalogue (produit+)>
<!ELEMENT produit (nom,photo,prixHT,TVA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT prixHT (#PCDATA)>
<!ELEMENT TVA (#PCDATA)>

<!ATTLIST catalogue année CDATA #REQUIRED>
<!ATTLIST produit codeP CDATA #REQUIRED>
<!ATTLIST produit catégorie CDATA #REQUIRED>
<!ATTLIST photo source CDATA #REQUIRED>

=== abdelalimah/XML/public/reproduction/2012/catalogue.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE catalogue SYSTEM "./catalogue.dtd">
<catalogue année="2012">
    <produit codeP="P01" catégorie="C1">
        <nom>PC Portable</nom>
        <photo source="P01.jpg"></photo>
        <prixHT>7000.00</prixHT>
        <TVA>20.00</TVA>
    </produit>
    <produit codeP="P02" catégorie="C1">
        <nom>PC Portable</nom>
        <photo source="P01.jpg"></photo>
        <prixHT>7000.00</prixHT>
        <TVA>20.00</TVA>
    </produit>
    <produit codeP="P03" catégorie="C2">
        <nom>PC Portable</nom>
        <photo source="P01.jpg"></photo>
        <prixHT>7000.00</prixHT>
        <TVA>20.00</TVA>
    </produit>
   
</catalogue>
