=== abdelalimah/XML/public/examsSolutions/2014/populationML.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="population">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pays" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string" minOccurs="1"></xs:element>
                            <xs:element name="population" type="xs:string" minOccurs="1"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="Code" type="codeType"></xs:attribute>
                        <xs:attribute name="continent" type="codeType"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="annÃ©e" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="codeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]+"></xs:pattern>
            <xs:maxLength value="2"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== abdelalimah/XML/public/examsSolutions/2014/population.xml
<?xml version="1.0"?>
<population annÃ©e="2013" xsi:noNamespaceSchemaLocation="./populationML.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <pays Code="DJ" continent="AF">
        <nom>Djibouti</nom>
        <population>792000</population>
    </pays>
    <pays Code="FR" continent="EU">
        <nom>France</nom>
        <population>65951611</population>
    </pays> 
    <pays Code="MA" continent="AF">
        <nom>Morocco</nom>
        <population>32940000</population>
    </pays>
</population>
