=== abdelalimah/XML/public/examsSolutions/2012/article.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="articles">
             <xs:complexType>
                 <xs:sequence>
                     <xs:element name="article" minOccurs="3" maxOccurs="unbounded">
                         <xs:complexType>
                             <xs:sequence>
                                 <xs:element name="référence" type="xs:string"></xs:element>
                                 <xs:element name="intitulé" type="intituleType"></xs:element>
                                 <xs:element name="prixTTC" type="prixTTCType"></xs:element>
                             </xs:sequence>
                             <xs:attribute name="cat" type="catType"></xs:attribute>
                         </xs:complexType>
                     </xs:element>
                 </xs:sequence>
             </xs:complexType>
            
    </xs:element>
    
    <xs:simpleType name="catType">
        <xs:restriction base="xs:string">
            <xs:pattern value="C1|C2"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="intituleType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="30"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="prixTTCType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{4},\d{2}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== abdelalimah/XML/public/examsSolutions/2012/articleML.xml
<?xml version="1.0" encoding="UTF-8"?>

<articles xsi:noNamespaceSchemaLocation="./article.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <article cat="C1">
        <référence>P01</référence>
        <intitulé>PC PORTABLE</intitulé>
        <prixTTC>8400,00</prixTTC>
    </article>
    <article cat="C2">
        <référence>P03</référence>
        <intitulé>IMPRIMANTE </intitulé>
        <prixTTC>2400,00</prixTTC>
    </article>
    <article cat="C2">
        <référence>P02</référence>
        <intitulé>LOGICIEL ANTIVIRUS </intitulé>
        <prixTTC>1050,00</prixTTC>
    </article>
</articles>
