=== abdelalimah/XML/public/examsSolutions/2012/catalogue.dtd
<!ELEMENT catalogue (produit+)>
<!ELEMENT produit (nom,photo,prixHT,TVA,desc?)>
<!ELEMENT nom (#PCDATA) >
<!ELEMENT photo EMPTY>
<!ELEMENT  prixHT (#PCDATA)>
<!ELEMENT TVA (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ATTLIST catalogue année CDATA #REQUIRED>
<!ATTLIST produit codeP ID #REQUIRED>
<!ATTLIST produit catégorie CDATA #REQUIRED>
<!ATTLIST photo source CDATA #REQUIRED>

=== abdelalimah/XML/public/examsSolutions/2012/catalogueML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogue SYSTEM "./catalogue.dtd">

<?xml-stylesheet href="./article.xsl" type="text/xsl"?>

<catalogue année = "2012">
    <produit codeP="P01" catégorie="C1">
    <nom>PC Portable</nom>
    <photo source="P01.jpg" />
    <prixHT>7000,00</prixHT>
    <TVA>20,00</TVA>
    </produit>
    <produit codeP="P02" catégorie="C2">
    <nom>Logiciel antivirus</nom>
    <photo source="P03.jpg" />
    <prixHT>1000,00</prixHT>
    <TVA>5,00</TVA>
    <desc>…</desc>
    </produit>
    <produit codeP="P03" catégorie="C1">
    <nom>Imprimante</nom>
    <photo source="P02.jpg" />
    <prixHT>2000,00</prixHT>
    <TVA>20,00</TVA>
    <desc>…</desc>
    </produit>
    <produit codeP="P04" catégorie="C2">
    <nom>CD de pilotes</nom>
    <photo source="P04.jpg" />
    <prixHT>0,00</prixHT>
    <TVA>0,00</TVA>
    <desc>…</desc>
    </produit>
    </catalogue>
